import "./globalcontext.css"
import React from "react"

const GlobalContext = React.createContext({
    monthIndex: 0,
    setMonthIndex: (index) => {},
    smallCalendarMonth: 0,
    setSmallCalendarMonth: (index) => {},
    daySelected: null,
    setDaySelected: (day) => {},
    showEventModal: false,
    setShowEventModal: () => {},
    dispatchCalEvent: ({ type, payload }) => {},
    savedEvents: [],
    selectedEvent: null,
    setSelectedEvent: () => {},
    selectedSeason: null,
    setSelectedSeason: () => {},
    selectedSession: null,
    setSelectedSession: () => {},
    setLabels: () => {},
    labels: [],
    updateLabel: () => {},
    filteredEvents: [],
    showSeasonModal: false,
    setShowSeasonModal: () => {},
    showSessionModal: false,
    setShowSessionModal: () => {},
    fetchData: () => {},
    seasonEvents: [],
    setSeasonEvents: ({ type, payload }) => {},
    filteredSeasonEvents: [],
    loaded: false,
    setLoaded: () => {},
    endDateSeasonMilliSeconds: [],
    setEndDateSeasonMilliSeconds: () => {},
    startDateSeasonMilliSeconds: [],
    setStartDateSeasonMilliSeconds: () => {},
    numberOfSessions: [],
    setNumberOfSessions: () => {},
    lastTrainingDayMilliSeconds: [],
    setLastTrainingDayMilliSeconds: () => {},
    durationLastTrainingSession: [], 
    setDurationLastTrainingSession: () => {},
    
})

export default GlobalContext;